<?php
// Copié une seule fois vers /config/config/config.php par l'entrypoint.
// Le compte par défaut est volontairement inutilisable : le vrai administrateur
// est /config/users/admin/config.php. Ainsi les comptes
// créés ensuite n'héritent jamais de allow_settings=true.
return [
    'username' => '__filesgallery_disabled_default__',
    'password' => '__FILES_GALLERY_DISABLED_PASSWORD_HASH__',
    'load_files_proxy_php' => true,
    'load_images' => true,
    // 0 n'est pas « illimité » : cela empêcherait de servir un original non
    // redimensionnable. 32 MiB couvre notamment les TIFF modestes.
    'load_images_max_filesize' => 33554432,
    'image_resize_enabled' => true,
    'image_resize_use_imagemagick' => true,
    'imagemagick_prefer_imagick' => true,
    'imagemagick_path' => 'convert',
    'imagemagick_image_types' => 'heif,heic,tiff,tif,psd,dng',
    'ffmpeg_path' => 'ffmpeg',
    'image_resize_cache' => true,
    'image_resize_cache_use_dir' => false,
    'image_resize_cache_direct' => false,
    'image_resize_dimensions' => 320,
    'image_resize_dimensions_retina' => 480,
    'image_resize_quality' => 85,
    'image_resize_memory_limit' => 256,
    'image_resize_max_pixels' => 60000000,
    'image_cache_validate_time' => true,
    'clean_cache_interval' => 7,
    'image_cache_max_last_access_time' => 90,
    'allow_symlinks' => false,
    'get_mime_type' => true,
    'files_exclude' => '/^\\./',
    'dirs_exclude' => '/(^|\\/)[.]/',
    'allow_all' => false,
    'allow_upload' => false,
    'allow_delete' => false,
    'allow_rename' => false,
    'allow_new_folder' => false,
    'allow_new_file' => false,
    'allow_duplicate' => false,
    'allow_text_edit' => false,
    'allow_zip' => false,
    'allow_unzip' => false,
    'allow_move' => false,
    'allow_copy' => false,
    'allow_download' => true,
    'allow_mass_download' => false,
    'allow_mass_copy_links' => false,
    'download_dir' => '',
    'allow_settings' => false,
    'allow_check_updates' => false,
    'allow_tests' => false,
    'allow_tasks' => false,
    'lang_default' => 'fr',
    'lang_auto' => true,
];
